remote_state {
  backend = "s3"
  config = {
    bucket         = "${local.aws_account_id}-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "${local.aws_region}"
    encrypt        = true
    dynamodb_table = "${local.aws_account_id}-lock"

    s3_bucket_tags = {
      owner = "terragrunt"
      name  = "Terraform State Storage"
    }

    dynamodb_table_tags = {
      owner = "terragrunt"
      name  = "Terraform Lock Table"
    }
  }
}

generate "main_providers" {
  path      = "autogenerated.main_providers.tf"
  if_exists = "overwrite"
  contents  = <<EOF
provider "aws" {
  region = "${local.aws_region}"
}
EOF
}

locals {
  aws_region = "sa-east-1"
  aws_account_id = "034506438324"
}